---
# Per environment values which override defaults in hmpps-immigration-detention-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: immigration-detention-ui-preprod.hmpps.service.justice.gov.uk

  env:
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    COURT_CASES_AND_RELEASE_DATES_URL: "https://court-cases-release-dates-preprod.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    DPS_PRISONER_URL: 'https://prisoner-preprod.digital.prison.service.justice.gov.uk'
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    INGRESS_URL: "https://immigration-detention-preprod.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMMON_COMPONENTS_ENABLED: 'true'
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts-non-prod
