---
# Per environment values which override defaults in hmpps-immigration-detention-ui/values.yaml

generic-service:
  ingress:
    host: immigration-detention.hmpps.service.justice.gov.uk

  env:
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    COURT_CASES_AND_RELEASE_DATES_URL: "https://court-cases-release-dates.hmpps.service.justice.gov.uk"
    DIGITAL_PRISON_SERVICES_URL: "https://digital.prison.service.justice.gov.uk"
    DPS_PRISONER_URL: 'https://prisoner.digital.prison.service.justice.gov.uk'
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    INGRESS_URL: "https://immigration-detention.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    COMMON_COMPONENTS_ENABLED: 'true'
    AUDIT_ENABLED: "false"
    FEATURES_MODIFY_NOMIS_RECORDS_ENABLED: "true"

generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts
